language: julia
dist: xenial
julia:
  - 1.3
  - 1.4
  - 1.5
matrix:
  include: 
    - os: linux
      arch: x86_64
    - os: osx
    - os: windows
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install visualstudio2017community; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install visualstudio2017-workload-nativedesktop; fi
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
